#!/bin/bash

#apache install script

#kontroll
APACHE2=$(dpkg -qury -W -f='$(status)' apache2 2>/dev/null | grep -c "ok installed")
 #käsutulemus kas 0 või 1
#kui = 0 siis tuleb paigaldada
if [ $APACHE2 -eq 0 ]; then
echo "paigaldame Apache2"
apt-get install -y apache2;
elif [ $APACHE2 -eq 1 ]; then
echo "apache2 paigladataud!"
service apache2 status
fi
